name = "caedforgex"
pages_build_output_dir = "./dist"
compatibility_date = "2024-02-19"

[[d1_databases]]
binding = "DB"
database_name = "cardforge-db"
database_id = "e4ab3f06-79c2-49de-830e-2ec99ea2f53e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cardforge-assets"

[vars]
API_KEY = "YOUR_GEMINI_KEY_HERE"
PUBLIC_R2_URL = "http://localhost:8787/r2"
